cookbook/urls.py
from django.urls import path

from . import views

app_name = 'cookbook'
urlpatterns = [ 
        path('', views.index, name='index'),
        path('new_recipe/', views.new_recipe, name='new_recipe'),
        path('edit_recipe/<recipe_id>', views.edit_recipe, name='edit_recipe'),
        path('display_recipe/<recipe_id>/', views.display_recipe, name='display_recipe'),
        path('browse_recipes/', views.browse_recipes, name='browse_recipes'),
        path('signup/', views.create_user, name='create_user'),
        path('login/', views.userLogin, name='login'),
        path('logout/', views.userLogout, name='logout'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cookbook/', include("cookbook.urls")),
    path('admin/', admin.site.urls),
]

cookbook/models.py
from django.db import models

# Create your models here.
class Contributor(models.Model): 
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class RecipeType(models.Model):
    name = models.CharField(max_length=100, default='no category')

    def __str__(self):
        return self.name

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    type = models.ForeignKey(RecipeType, on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(Contributor, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500, blank=True)
    ingredients = models.TextField(max_length=2000, default='none specified')
    instructions = models.TextField(max_length=2000)

    def __str__(self):
        return self.name

cookbook/forms.py
from django import forms

# These are used to generate the recipe categories in the dropdown box 
# on the recipe entry form
RECIPE_TYPES = [
        ('', 'Select'),
        ('Bread and Breakfast', 'Bread and Breakfast'),
        ('Appetizer', 'Appetizer'),
        ('Dessert', 'Dessert'),
        ('Recipe From Famous Person', 'Recipe From Famous Person'),
        ('Recipe For Kids', 'Recipe For Kids'),
        ('Holiday Recipe', 'Holiday Recipe'),
        ('Main Dish', 'Main Dish'),
        ('Miscellaneous - Jams, Sauces, Beverages', 
            'Miscellaneous - Jams, Sauces, Beverages'),
        ('Salad', 'Salad'),
        ('Side Dish - Vegetables', 'Side Dish - Vegetables'),
        ('Soup', 'Soup'),
]

class RecipeForm(forms.Form): 
    recipe_name = forms.CharField(label="Recipe Name", 
            widget=forms.TextInput(attrs={'class':'form-control',
                'placeholder':'Enter recipe name'}), max_length=100)
    recipe_type = forms.CharField(label='Recipe Category', 
            widget=forms.Select(choices=RECIPE_TYPES))
    author = forms.CharField(label="Author", 
            widget=forms.TextInput(attrs={'class':'form-control',
                'placeholder':'Enter author name'}), max_length=100)
    comment = forms.CharField(label="Comment", 
            widget=forms.Textarea(attrs={'class':'form-control',
                'placeholder':'Enter a short comment about the recipe',
                'rows':'5'}), max_length=500)
    ingredients = forms.CharField(label="Ingredients", 
            widget=forms.Textarea(attrs={'class':'form-control',
                'placeholder':'Enter ingredients with amounts, separated by'\
                        ' commas','rows':'5'}), max_length=2000)
    instructions = forms.CharField(label="Instructions",
            widget=forms.Textarea(attrs={'class':'form-control',
                'placeholder':'Enter instructions for recipe','rows':'5'}), 
                max_length=2000)

class NewUserForm(forms.Form):
    first_name = forms.CharField(label="First Name:", 
            widget=forms.TextInput(attrs={'cols':10, 'class':'form-control',
                'placeholder':'Enter First Name'}), max_length=100)
    last_name= forms.CharField(label="Last Name:", 
            widget=forms.TextInput(attrs={'class':'form-control',
                'placeholder':'Enter Last Name'}), max_length=100)
    username = forms.CharField(label="Username:", 
            widget=forms.TextInput(attrs={'class':'form-control',
                'placeholder':'Enter Username'}), max_length=100)
    password = forms.CharField(label="Enter Password:", 
            widget=forms.TextInput(attrs={'class':'form-control',
                'placeholder':'Enter Password'}), max_length=100)

class LoginForm(forms.Form):
    username = forms.CharField(label="Username:", 
            widget=forms.TextInput(attrs={'class':'form-control',
                'placeholder':'Enter Username'}), max_length=100)
    password = forms.CharField(label="Enter Password:", 
            widget=forms.TextInput(attrs={'class':'form-control',
                'placeholder':'Enter Password'}), max_length=100)

cookbook/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django import forms
from .forms import RecipeForm, NewUserForm, LoginForm
from cookbook.models import Contributor, RecipeType, Recipe
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.
def index(request): 
    return render(request, "cookbook/index.html")

# Page containing the form to create a new recipe
@login_required(login_url="/cookbook/login/")
@permission_required('cookbook.add_recipe',raise_exception=True)
def new_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            # find if author already exists in db, create new db entry if not
            name = form.cleaned_data['author']
            authorSet = Contributor.objects.filter(name__startswith=name)
            nMatches = len(authorSet)
            if nMatches == 0:
                contributorDbEntry = Contributor(name=name)
            elif nMatches == 1:
                contributorDbEntry = authorSet.first()
            # TODO: handle multiple matches
            elif nMatches > 1:
                contributorDbEntry = authorSet.first()
            contributorDbEntry.save()

            # Get recipe type db entry
            recipeType = form.cleaned_data['recipe_type']
            type_set = RecipeType.objects.filter(name__startswith=recipeType)
            if len(type_set) == 0: 
                typeDbEntry = RecipeType(name=recipeType)
            else:
                typeDbEntry = type_set.first()
            typeDbEntry.save()

            # Create new recipe db entry
            recipeNameInput = form.cleaned_data['recipe_name']
            commentInput = form.cleaned_data['comment']
            ingredientsInput = form.cleaned_data['ingredients']
            instructionsInput = form.cleaned_data['instructions']
            newRecipeDbEntry = Recipe(name=recipeNameInput, 
                    type=typeDbEntry, 
                    author=contributorDbEntry, 
                    comment=commentInput, 
                    ingredients=ingredientsInput, 
                    instructions=instructionsInput)
            newRecipeDbEntry.save()

            return HttpResponseRedirect('/cookbook/')
    else: 
        form = RecipeForm()
    return render(request, "cookbook/create_recipe.html", {'form':form})

@login_required(login_url="/cookbook/login/")
@permission_required('cookbook.change_recipe', raise_exception=True)
def edit_recipe(request, recipe_id): 
    try: 
        recipe = Recipe.objects.get(pk=recipe_id)
    except: 
        raise Http404("Recipe not found")
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        if form.is_valid():
            # find if author already exists in db, create new db entry if not
            name = form.cleaned_data['author']
            authorSet = Contributor.objects.filter(name__startswith=name)
            nMatches = len(authorSet)
            if nMatches == 0:
                contributorDbEntry = Contributor(name=name)
            elif nMatches == 1:
                contributorDbEntry = authorSet.first()
            # TODO: handle multiple matches
            elif nMatches > 1:
                contributorDbEntry = authorSet.first()
            contributorDbEntry.save()

            # Get recipe type db entry
            recipeType = form.cleaned_data['recipe_type']
            type_set = RecipeType.objects.filter(name__startswith=recipeType)
            if len(type_set) == 0: 
                typeDbEntry = RecipeType(name=recipeType)
            else:
                typeDbEntry = type_set.first()
            typeDbEntry.save()

            recipe.name = form.cleaned_data['recipe_name']
            recipe.type = typeDbEntry
            recipe.author = contributorDbEntry
            recipe.comment = form.cleaned_data['comment']
            recipe.ingredients =  form.cleaned_data['ingredients']
            recipe.instructions  = form.cleaned_data['instructions']
            recipe.save()
            return HttpResponseRedirect(f'/cookbook/display_recipe/{recipe_id}')
    else:
        form = RecipeForm(initial={"recipe_name":recipe.name,
                "recipe_type":recipe.type.name, 
                "author":recipe.author.name, 
                "comment":recipe.comment, 
                "ingredients":recipe.ingredients, 
                "instructions":recipe.instructions})
    return render(request, 'cookbook/edit_recipe.html',
            {'form':form, 'recipe_id':recipe.id})

# Display a recipe
def display_recipe(request, recipe_id): 
    try: 
        recipe = Recipe.objects.get(pk=recipe_id)
        ingredients_list = recipe.ingredients.split(',')
    except: 
        raise Http404("Recipe not found")
    return render(request, 'cookbook/display_recipe.html',{'recipe':recipe, 
        "ingredients":ingredients_list})

def browse_recipes(request):
    try:
        recipes = Recipe.objects.all().order_by('name')
    except: 
        raise Http404("Oops")
    return render(request, 'cookbook/browse_recipes.html', {'recipes':recipes})

def create_user(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password'] 
            first = form.cleaned_data['first_name']
            last = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            user = User.objects.create_user(username, first_name=first, 
                    last_name=last, password=password)
            user = authenticate(username=username, password=password)
            if user is not None: 
                login(request, user)
            return HttpResponseRedirect("/cookbook/")
    else: 
        form = NewUserForm()
    return render(request, 'cookbook/signup.html', {'form':form})

def userLogin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password'] 
            user = authenticate(username=username, password=password)
            if user is not None: 
                login(request, user)
                return HttpResponseRedirect('/cookbook/')
            else: 
                form = LoginForm()
    else: 
        form = LoginForm()
    return render(request, 'cookbook/login.html', {'form':form})

def userLogout(request): 
    logout(request)
    return HttpResponseRedirect('/cookbook/')

cookbook/templates/cookbook/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock title %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Stasney-Dean Cookbook</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'cookbook:index' %}">Home</a></li>
      <li><a href="{% url 'cookbook:browse_recipes' %}">Browse Recipes</a></li>
      <li><a href="{% url 'cookbook:new_recipe' %}">Create New Recipe</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li>
        <span class="navbar-text"> 
          Currently logged in as {{ user.username}} 
        </span>
      </li>
      <li>
        <a href="{% url 'cookbook:logout' %}"><span class="glyphicon glyphicon-log-in">
          </span> Logout
        </a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'cookbook:create_user' %}">
          <span class="glyphicon glyphicon-user"></span> Sign Up
        </a>
      </li>
      <li>
        <a href="{% url 'cookbook:login' %}">
          <span class="glyphicon glyphicon-log-in"></span> Login
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% block content %}{% endblock content %}
</body>
</html>

cookbook/templates/cookbook/browse_recipes.html
{% extends "cookbook/base.html" %}
{% block title %}Browse Recipes{% endblock title %}

{% block content %}
<div class="container">
  <h2>Recipes List</h2>
  <p>The table is searchable by recipe name, author, and type</p>  
  <input class="form-control" id="myInput" type="text" placeholder="Search..">
  <br>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Recipe Name</th>
        <th>Author</th>
        <th>Type</th>
        <th>Recipe Link</th>
      </tr>
    </thead>
    <tbody id="myTable">
      {% for recipe in recipes %} 
      <tr>
        <td> {{ recipe.name }} </td>
        <td> {{ recipe.author }} </td>
        <td> {{ recipe.type }} </td>
        <td> <a href="{% url 'cookbook:display_recipe' recipe.id %}">view</a>
          | <a href="{% url 'cookbook:edit_recipe' recipe.id %}">edit</a>
        </td>

      </tr> 
      {% endfor %}
    </tbody>
  </table>
</div>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{% endblock content %}

cookbook/templates/cookbook/create_recipe.html
{% extends "cookbook/base.html" %}
{% block title%}Create Recipe{% endblock title %}

{% block content %}  
<div class="container">
  <h2>Enter New Recipe</h2>
  <div class="well">
  <form action="{% url 'cookbook:new_recipe' %}" id="recipe_form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save & Submit" class='btn btn-primary'>
  </form>
  </div>
</div>
{% endblock content %}

cookbook/templates/cookbook/display_recipe.html
{% extends "cookbook/base.html" %}
{% block title %}{{ recipe.name }}{% endblock title %}
{% block content %}
<div class="container">
  <div class="well">
  <h1> {{ recipe.name }} <small>by {{ recipe.author }} </small> </h1>
  <p> {{ recipe.comment }}</p>
  <h3> Ingredients: </h3>
      <div>
        <ul class="columns" data-columns="2">
          {% for ingredient in ingredients %}
            <li> {{ ingredient }} </li>
          {% endfor %}
        </ul>
      </div>
  <h3> Instructions: </h3>
  <pre style="font-family:helvetica; white-space:pre-wrap;">{{ recipe.instructions }}</pre>
  </div>
</div>
{% endblock content %}

cookbook/templates/cookbook/edit_recipe.html
{% extends "cookbook/base.html" %}
{% block title%}Edit Recipe{% endblock title %}

{% block content %}  
<div class="container">
  <h2>Edit Recipe</h2>
  <div class="well">
  <form action="{% url 'cookbook:edit_recipe' recipe_id %}" id="recipe_form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save & Submit" class='btn btn-primary'>
  </form>
  </div>
</div>
{% endblock content %}

cookbook/templates/cookbook/index.html
{% extends "cookbook/base.html" %}
{% block title%}Home{% endblock title %}

{% block content %}  
<div class="container">
  <h3>Welcome to the Stasney-Dean Cookbook Site!</h3>
  <p>Here you can create, edit, and view recipes as part of the 2020 
  Stasney-Dean Family Cookbook.</p>
  <p>To start, you'll need to create an account. After that, I'll approve your
  account, and then you can get to creating recipes! In the mean time, you'll
  still be able to view recipes that have already been created.</p>
  <p> If you have any questions, e-mail me at frankie.betanco@gmail.com</p>
</div>
{% endblock content %}

cookbook/templates/cookbook/login.html
{% extends "cookbook/base.html" %}
{% block title%}Log in{% endblock title %}

{% block content %}  
<div class="container">
  <div class="row">
    <div class="col-sm-4">
    <div class="well">
    <form action="{% url 'cookbook:login' %}" id="login" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Log in" class='btn btn-primary'>
    </form>
    </div>
    </div>
  </div>
  <p> 
    Don't have an account? 
    <a href={% url "cookbook:create_user" %}>Create one<a>
  </p>
</div>
{% endblock content %}

cookbook/templates/cookbook/signup.html
{% extends "cookbook/base.html" %}
{% block title%}Sign up{% endblock title %}

{% block content %}  
<div class="container">
  <div class="row">
    <div class="col-sm-4">
    <div class="well">
    <form action="{% url 'cookbook:create_user' %}" id="create_user" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Sign up" class='btn btn-primary'>
    </form>
    </div>
    </div>
  </div>
</div>
{% endblock content %}